async function go() {}

go().catch((error) => {
  console.error(error);
});
